export { default as About } from './About'
export { default as Cart } from './Cart'
export { default as Checkout } from './Checkout'
export { default as Error } from './Error'
export { default as Home } from './Home'
export { default as Orders } from './Orders'
export { default as LoginPage } from './LoginPage'
export { default as SignUpPage } from './SignUpPage'
export { default as Products } from './Products'
export { default as SingleProduct } from './SingleProduct'
export { default as Landing} from './Landing'
